"""
Pure Python PNG Icon Generator for Lucky48.

Creates high-quality, standalone application icons using smooth anti-aliasing
without external image dependencies (uses standard library `zlib` and `struct`).
"""

import logging
import math
import struct
import zlib
from pathlib import Path
from typing import Callable, Tuple

# Configure logging for standard utility output
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger("IconGenerator")

# Pixel drawer type alias: (x, y, width, height) -> (R, G, B, A)
PixelCallback = Callable[[int, int, int, int], Tuple[int, int, int, int]]


def create_png(width: int, height: int, draw_func: PixelCallback) -> bytes:
    """
    Encodes raw RGBA pixel data generated by `draw_func` into a standard PNG format.
    
    Args:
        width: Canvas width in pixels.
        height: Canvas height in pixels.
        draw_func: Callable returning (r, g, b, a) tuples for given coordinates.
        
    Returns:
        bytes: Complete binary stream of the PNG file.
    """
    raw_data = bytearray()
    
    for y in range(height):
        raw_data.append(0)  # Filter type 0: None (per scanline)
        for x in range(width):
            r, g, b, a = draw_func(x, y, width, height)
            raw_data.extend([r, g, b, a])

    def build_chunk(chunk_type: bytes, data: bytes) -> bytes:
        content = chunk_type + data
        crc = zlib.crc32(content) & 0xFFFFFFFF
        return struct.pack(">I", len(data)) + content + struct.pack(">I", crc)

    header = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)  # 8-bit RGBA
    idat = zlib.compress(bytes(raw_data), level=9)

    return (
        header
        + build_chunk(b"IHDR", ihdr)
        + build_chunk(b"IDAT", idat)
        + build_chunk(b"IEND", b"")
    )


def lucky48_icon_pixel(x: int, y: int, w: int, h: int) -> Tuple[int, int, int, int]:
    """
    Renders a vector-like Lucky48 badge with smooth anti-aliasing.
    
    Features:
    - Golden outer ring (#f59e0b)
    - Dark navy blue inner core (#0f172a)
    - Sub-pixel edge smoothing for pristine scaling
    """
    cx, cy = (w - 1) / 2.0, (h - 1) / 2.0
    r_outer = w * 0.46
    r_inner = w * 0.38
    
    # Distance from current pixel center
    dist = math.hypot((x + 0.5) - cx, (y + 0.5) - cy)
    
    # Smooth boundary transitions (anti-aliasing width = 1 pixel)
    edge_outer = max(0.0, min(1.0, r_outer + 0.5 - dist))
    edge_inner = max(0.0, min(1.0, r_inner + 0.5 - dist))

    if edge_outer <= 0:
        return 0, 0, 0, 0  # Fully transparent

    # Palette definition (RGBA)
    gold = (245, 158, 11, 255)       # #f59e0b
    navy = (15, 23, 42, 255)         # #0f172a

    if edge_inner >= 1.0:
        # Fully inside inner core
        return navy
    elif edge_inner > 0.0:
        # Blend between inner core and golden border
        r = int(navy[0] * edge_inner + gold[0] * (1.0 - edge_inner))
        g = int(navy[1] * edge_inner + gold[1] * (1.0 - edge_inner))
        b = int(navy[2] * edge_inner + gold[2] * (1.0 - edge_inner))
        return r, g, b, 255
    else:
        # Blend outer golden edge with alpha transparency
        r, g, b, _ = gold
        alpha = int(255 * edge_outer)
        return r, g, b, alpha


def generate_icons(output_dir: Path = Path(".")) -> None:
    """Generates standard resolution variants of the Lucky48 application icon."""
    target_sizes = [192, 512]
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    for size in target_sizes:
        file_path = output_dir / f"icon-{size}.png"
        logger.info(f"Rendering {size}x{size} icon...")
        
        png_data = create_png(size, size, lucky48_icon_pixel)
        file_path.write_bytes(png_data)
        
        logger.info(f"Successfully generated: {file_path.resolve()}")


if __name__ == "__main__":
    generate_icons()